"""Public batch-processing API.

Implementation is split into focused modules so GUI, CLI, review persistence,
and file I/O can evolve independently while keeping the historical import
surface stable.
"""

from __future__ import annotations

import shutil
from dataclasses import replace
from pathlib import Path

from .anatomy_filter import AnatomyAwareDetector
from .i18n import t
from .pipeline_config import PipelineConfig
from .pipeline_logging import JsonlRunLogger, write_jsonl_log
from .pipeline_processor import BatchProcessor as _BatchProcessor
from .pipeline_processor import discover_images, validate_processing_paths
from .pipeline_review import write_review_html


class BatchProcessor(_BatchProcessor):
    """Batch processor with public UX/safety policy layers.

    In addition to the historical count-review behavior, the default detector
    is wrapped by a conservative anatomy sanity filter. The filter can only
    remove a candidate when reliable pose evidence places it near a knee or
    armpit and clearly away from the pelvis. Missing/ambiguous pose data always
    fails open and keeps the original detector result.

    Manual-review bundles generated by ``process_folder`` are reorganized into
    three explicit purposes:

    ``edit``
        Original, untouched source image. This is the file users should edit.
    ``reference_bbox``
        Annotated reference image showing what the detector selected.
    ``auto_censored``
        Automatic censor result, kept only for side-by-side comparison.
    """

    def __init__(self, config: PipelineConfig | None = None, detector=None):
        super().__init__(config=config, detector=detector)
        # Custom detectors supplied by callers/tests are preserved exactly.
        if detector is None and not isinstance(self.detector, AnatomyAwareDetector):
            self.detector = AnatomyAwareDetector(self.detector)

    def _reset_anatomy_diagnostics(self) -> None:
        reset = getattr(self.detector, "reset_filter_state", None)
        if callable(reset):
            reset()

    def _attach_anatomy_diagnostics(self, result):
        filter_result = getattr(self.detector, "last_filter_result", None)
        if filter_result is None:
            return result
        return replace(
            result,
            anatomy_suppressed=tuple(item.detection for item in filter_result.suppressed),
            anatomy_suppression_reasons=tuple(item.log_reason for item in filter_result.suppressed),
            anatomy_filter_status=str(filter_result.status),
        )

    def process_file(
        self,
        source,
        output,
        review_copy=None,
        manual_review_copy=None,
        manual_review_annotated=None,
        preview=None,
        stop_requested=None,
    ):
        self._reset_anatomy_diagnostics()

        if not self.config.review_only_over_count:
            result = super().process_file(
                source,
                output,
                review_copy,
                manual_review_copy,
                manual_review_annotated,
                preview,
                stop_requested,
            )
            return self._attach_anatomy_diagnostics(result)

        expected = self.config.expected_person_count

        def preview_proxy(frame):
            if preview is None:
                return
            count = len(frame.detections)
            if frame.stage == "detected" and count <= expected:
                if count == 0:
                    status = t(
                        self.config.language,
                        "対象未検出（正常扱い）",
                        "No target detected (treated as normal)",
                    )
                else:
                    status = t(
                        self.config.language,
                        f"検出完了: {count}件",
                        f"Detection complete: {count}",
                    )
                frame = replace(frame, status=status)
            elif frame.stage == "censored" and count == 0:
                frame = replace(
                    frame,
                    status=t(
                        self.config.language,
                        "対象未検出: 元画像をそのまま保存",
                        "No target detected: original image copied unchanged",
                    ),
                )
            preview(frame)

        result = super().process_file(
            source,
            output,
            review_copy,
            manual_review_copy,
            manual_review_annotated,
            preview_proxy if preview is not None else None,
            stop_requested,
        )
        result = self._attach_anatomy_diagnostics(result)

        if result.error or result.cancelled or result.skipped or result.fatal_error:
            return result

        over_detected = len(result.detections) > expected
        manual_bundle = _manual_review_bundle_paths(manual_review_copy)

        if over_detected:
            if manual_bundle is not None:
                edit_path, bbox_path, auto_path = manual_bundle
                _move_if_exists(manual_review_copy, edit_path)
                _move_if_exists(manual_review_annotated, bbox_path)
                if result.output is not None and result.output.exists():
                    auto_path.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(result.output, auto_path)
                return replace(result, manual_review_path=edit_path)
            return result

        # A successful re-run that is no longer over-detected should remove all
        # stale manual-review artifacts, including the new edit/reference/auto
        # bundle. The base processor already removes legacy original/annotated
        # files; this cleans the reorganized locations as well.
        if manual_bundle is not None:
            for path in manual_bundle:
                path.unlink(missing_ok=True)

        if result.count_mismatch:
            for path in (manual_review_copy, manual_review_annotated):
                if path is not None:
                    path.unlink(missing_ok=True)
            return replace(result, count_mismatch=False, manual_review_path=None)
        return result


def _manual_review_bundle_paths(manual_review_copy: Path | None) -> tuple[Path, Path, Path] | None:
    """Map the processor's legacy ``original`` path to the manual-edit bundle.

    Only paths generated by ``BatchProcessor.process_folder`` are rewritten.
    Direct callers that provide an arbitrary ``manual_review_copy`` path retain
    the historical behavior for API compatibility.
    """

    if manual_review_copy is None:
        return None
    original_path = Path(manual_review_copy)
    original_root = next(
        (
            parent
            for parent in original_path.parents
            if parent.name == "original" and parent.parent.name == "_manual_review"
        ),
        None,
    )
    if original_root is None:
        return None
    relative = original_path.relative_to(original_root)
    root = original_root.parent
    return (
        root / "edit" / relative,
        root / "reference_bbox" / relative,
        root / "auto_censored" / relative,
    )


def _move_if_exists(source: Path | None, destination: Path) -> None:
    if source is None:
        return
    source = Path(source)
    if not source.exists():
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.unlink(missing_ok=True)
    source.replace(destination)


__all__ = [
    "BatchProcessor",
    "PipelineConfig",
    "JsonlRunLogger",
    "discover_images",
    "validate_processing_paths",
    "write_jsonl_log",
    "write_review_html",
]
